name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "inicia login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "fin login"

    - name: build docker image
      run: |
        docker build -t zombypop/docker-graphql:1.0.0 . 

    - name: push docker image
      run: |
        docker push zombypop/docker-graphql:1.0.0
